name: Market Weather Diagnostic Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/diagnostic-market-weather.yml'
      - 'market-weather-functions.R'
      - 'market-weather-indices.R'
      - 'market-weather.qmd'
      - 'market-weather.css'

jobs:
  comprehensive-diagnosis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: System Information and Diagnostics
        run: |
          echo "Operating System:"
          cat /etc/os-release
          echo "-------------------------"
          echo "Current User:"
          whoami
          echo "-------------------------"
          echo "Current Directory:"
          pwd
          echo "-------------------------"
          echo "R and Package Installation Diagnostic Info:"
          R --version
          echo "-------------------------"
          echo "System Requirements Check:"
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfreetype6-dev \
            libpng-dev \
            libmagick++-dev \
            pandoc

      - name: Install R and Required Packages
        run: |
          # Explicit libcurl installation
          sudo apt-get install -y libcurl4-openssl-dev

          # Install R packages with verbose output and error handling
          R -e "
          # Function to install packages with robust error handling
          install_robust <- function(packages) {
            for (pkg in packages) {
              tryCatch({
                if (!require(pkg, character.only = TRUE)) {
                  install.packages(pkg, repos = 'https://cloud.r-project.org', 
                                   lib = .libPaths()[1], 
                                   dependencies = c('Depends', 'Imports', 'LinkingTo'))
                  library(pkg, character.only = TRUE)
                  cat(sprintf('Successfully installed and loaded %s\n', pkg))
                }
              }, error = function(e) {
                cat(sprintf('Error installing %s: %s\n', pkg, e$message))
                quit(status = 1)
              })
            }
          }

          # List of packages to install
          packages_to_install <- c(
            'tidyverse', 
            'quantmod', 
            'rvest', 
            'httr', 
            'jsonlite', 
            'lubridate', 
            'DT', 
            'scales'
          )

          # Attempt package installation
          install_robust(packages_to_install)

          # Verify installations
          installed_packages <- installed.packages()[,1]
          missing_packages <- setdiff(packages_to_install, installed_packages)
          
          if (length(missing_packages) > 0) {
            cat('Failed to install the following packages:\n')
            cat(missing_packages, sep = '\n')
            quit(status = 1)
          } else {
            cat('All required packages installed successfully!\n')
          }
          "

      - name: Install Quarto
        run: |
          # Download and install Quarto
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb
          sudo dpkg -i quarto-1.4.549-linux-amd64.deb
          quarto --version

      - name: Validate R Environment
        run: |
          R -e "
          # Check package versions
          package_versions <- lapply(
            c('tidyverse', 'quantmod', 'rvest', 'httr', 'jsonlite', 'lubridate', 'DT', 'scales'), 
            function(pkg) packageVersion(pkg)
          )
          names(package_versions) <- c('tidyverse', 'quantmod', 'rvest', 'httr', 'jsonlite', 'lubridate', 'DT', 'scales')
          print(package_versions)
          "

      - name: Verify File Dependencies
        run: |
          # Check for required files
          required_files=(
            "market-weather.qmd"
            "market-weather-functions.R"
            "market-weather-indices.R"
            "market-weather.css"
          )
          
          all_files_exist=true
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              all_files_exist=false
            else
              echo "✅ Found $file"
              file "$file"  # Display file type and encoding
            fi
          done
          
          if [ "$all_files_exist" = false ]; then
            exit 1
          fi

      - name: Render Quarto Document
        run: |
          quarto render market-weather.qmd \
            --output-dir _site || {
              echo "Quarto rendering failed"
              exit 1
            }
          
          ls -la _site
          
          if [ -f "_site/market-weather.html" ]; then
            echo "HTML file successfully generated"
            head -n 50 "_site/market-weather.html"
          else
            echo "No HTML file generated"
            exit 1
          fi

      - name: Debug Output
        if: failure()
        run: |
          echo "R Library Paths:"
          R -e ".libPaths()"
          
          echo "-------------------------"
          echo "Installed Packages:"
          R -e "installed.packages()[,1]"
          
          echo "-------------------------"
          echo "System Package Information:"
          dpkg -l | grep -E 'libcurl|libssl|libxml2|libharfbuzz|libfreetype|libpng|pandoc'
