name: Market Weather Update

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3

  render:
    needs: cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450

      - name: Get R package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ runner.os }}-${{ hashFiles('**/market-weather.qmd') }}
          restore-keys: r-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Install R packages
        run: |
          install.packages(c(
            'tidyverse',
            'quantmod',
            'tidyquant',
            'rvest',
            'httr',
            'jsonlite',
            'kableExtra',
            'lubridate',
            'DT'
          ), repos = 'https://cloud.r-project.org')
        shell: Rscript {0}

      - name: Verify file structure
        run: |
          echo "Checking required files..."
          for file in market-weather.qmd market-weather-functions.R market-weather-indices.R market-weather.css; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file not found"
              exit 1
            fi
          done

      - name: Create _quarto.yml
        run: |
          cat << EOF > _quarto.yml
          project:
            type: website
            output-dir: _site
            render:
              - market-weather.qmd
          format:
            html:
              embed-resources: true
              self-contained: true
              theme: none
              css: market-weather.css
          EOF

      - name: Render Market Weather
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Rendering with Quarto..."
          quarto render market-weather.qmd
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

      - name: Check deployment
        run: |
          if [ -d "_site" ] && [ -f "_site/market-weather.html" ]; then
            echo "Deployment check passed"
          else
            echo "Deployment check failed - output files missing"
            exit 1
          fi
