name: Market Weather Update

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:        # Manual trigger option

jobs:
  update-market-weather:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libglpk-dev \
            libgit2-dev \
            pandoc

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.549'
          tinytex: true

      - name: Verify required files
        run: |
          required_files=("market-weather.qmd" "market-weather-functions.R" "market-weather.css")
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file not found"
              exit 1
            fi
            echo "✓ Found $file"
          done

      - name: Install R packages
        shell: Rscript {0}
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          required_packages <- c('tidyverse', 'quantmod', 'rvest', 'httr', 'jsonlite', 'lubridate', 'DT')
          install_if_missing <- function(packages) {
            new_packages <- packages[!(packages %in% installed.packages()[,"Package"])]
            if(length(new_packages)) install.packages(new_packages)
          }
          install_if_missing(required_packages)
          lapply(required_packages, function(pkg) {
            if(!require(pkg, character.only = TRUE)) stop(paste("Failed to load package:", pkg))
            print(paste("✓ Loaded:", pkg))
          })

      - name: Test R environment
        shell: Rscript {0}
        run: |
          print("Testing R environment...")
          print(sessionInfo())
          print("Testing source file...")
          source("market-weather-functions.R")
          print("✓ Environment check complete")

      - name: Render report
        run: |
          quarto render market-weather.qmd --output-dir _site
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
