name: Market Weather Update

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:        # Manual trigger option
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Updated to latest stable R version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            pandoc \
            cmake

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.9'  # Latest stable version

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: prerelease  # Use latest prerelease version

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create data directories
        run: |
          mkdir -p data/cache
          mkdir -p data/backup

      - name: Verify required files
        run: |
          required_files=(
            "market-weather.qmd"
            "market-weather-functions.R"
            "market-weather-indices.R"
            "market-weather.css"
          )
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
            echo "✅ Found $file"
          done

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::quantmod
            any::rvest
            any::httr
            any::jsonlite
            any::lubridate
            any::DT
            any::scales
          cache: true

      - name: Render Quarto Project
        run: |
          quarto render market-weather.qmd
          
          # Ensure output directory exists
          mkdir -p _site
          
          # Move rendered files to _site
          mv market-weather.html _site/index.html
          
          # Create .nojekyll file
          touch _site/.nojekyll
          
          # Create timestamp
          date -u > _site/build_timestamp.txt

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Optional: Error handling and notification
  error-handling:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue on Failure
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Market Weather Update Workflow Failed',
              body: `Workflow failed for commit ${context.sha}. 
              
See the [Actions tab](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
            })
